App\DTO\Pastry\PastryDTO:
  properties:
    name:
      - Type: string
      - NotBlank: ~
    price:
      - Type: float
      - NotBlank: ~
    categoryId:
      - Type: integer
      - NotBlank: ~
    subCollectionId:
      - Type: integer
      - NotBlank: ~
    flavourId:
      - Type: integer
      - NotBlank: ~
    orderBy:
      - Type: string
      - NotBlank: ~
