App\DTO\Order\OrderDTO:
  properties:
    id:
      - Type: integer
      - NotBlank: ~
    userId:
      - Type: integer
      - NotBlank: ~
    orderStatusId:
      - Type: integer
      - NotBlank: ~
