App\DTO\BasketContent\BasketContentDTO:
  properties:
    quantity:
      - Type: integer
      - NotBlank: ~
    pastryId:
      - Type: integer
      - NotBlank: ~
    formatId:
      - Type: integer
