App\DTO\User\UserDTO:
  properties:
    firstName:
      - Type: string
      - NotBlank: ~
    lastName:
      - Type: string
      - NotBlank: ~
    password:
      - Type: string
      - NotBlank: ~
    email:
      - Type: string
      - NotBlank: ~
    roleId:
      - Type: integer
      - NotBlank: ~
    phoneNumber:
      - Type: string
      - NotBlank: ~
      - Regex: '/^0[1|2|3|4|5|6|7|9][0-9]{8}$/'