App\DTO\User\UpdateUserDTO:
  properties:
    firstName:
      - Type: string
      - NotBlank: ~
    lastName:
      - Type: string
      - NotBlank: ~
    email:
      - Type: string
      - NotBlank: ~
    phoneNumber:
      - Type: string
      - NotBlank: ~
      - Regex: '/^0[1|2|3|4|5|6|7|9][0-9]{8}$/'
    city:
      - Type: string
      - NotBlank: ~
    zipCode:
      - Type: string
      - NotBlank: ~
    street:
      - Type: string
      - NotBlank: ~